name = "Rastreio.IO"
client_id = "2531fe45558ab25cfda4259051031c07"
application_url = "https://rastreio-io.vercel.app"
embedded = false

[access_scopes]
scopes = "read_orders,write_orders,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = ["https://rastreio-io.vercel.app/api/shopify/oauth/callback"]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
